# Generated by Django 3.1.5 on 2021-01-17 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, error_messages={'invalid_extension': 'Этот формат не поддерживается. Только jpg'}, upload_to='images/product/', validators=[product.models.Product.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg'))], verbose_name='Изображения'),
        ),
        migrations.CreateModel(
            name='ListTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок списка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Заголовк списка',
                'verbose_name_plural': 'Заголовк списка',
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=250, verbose_name='Пункт списка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.listtitle')),
            ],
            options={
                'verbose_name': 'Пункт списка',
                'verbose_name_plural': 'Пункт списка',
            },
        ),
    ]
