# Generated by Django 3.1.5 on 2021-01-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210117_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'verbose_name': 'Пункт списка', 'verbose_name_plural': 'Пункты списков'},
        ),
        migrations.AlterModelOptions(
            name='listtitle',
            options={'verbose_name': 'Заголовок списка', 'verbose_name_plural': 'Заголовоки списков'},
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlistitem', to='product.listtitle', verbose_name='Выбрать заголовок'),
        ),
        migrations.AlterField(
            model_name='listtitle',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productlisttitle', to='product.product'),
        ),
    ]
