# Generated by Django 3.1.5 on 2021-01-16 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.RemoveField(
            model_name='main',
            name='img',
        ),
        migrations.RemoveField(
            model_name='main',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='main',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='main',
            name='text',
        ),
        migrations.AddField(
            model_name='map',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.main'),
        ),
        migrations.AddField(
            model_name='text',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.main'),
        ),
    ]
