# Generated by Django 3.1.5 on 2021-01-17 15:26

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210116_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='main',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=250, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='main',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='images',
            field=models.ImageField(error_messages={'invalid_extension': 'Этот формат не поддерживается. Только jpg'}, upload_to='images/slider/', validators=[main.models.SliderImage.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg'))], verbose_name='Картинка'),
        ),
    ]
